version: "3.9"
services:
  node-app:
    image: registry.gitlab.com/kartik1225/docker_node_sample
    build: .
    #    ports:
    #      - "1000:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - app-mongo
    env_file:
      - .env
#    deploy:
#      replicas: 6
#      restart_policy:
#        condition: on-failure
#      update_config:
#        parallelism: 2
#        delay: 10s
#        order: stop-first
  app-mongo:
    image: mongo:5.0.6-focal
    restart: always
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  app-nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
    environment:
      #      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
volumes:
  mongo-db:
